# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Karma' do
	pod 'FontAwesomeIconFactory'
	pod 'Parse'
	pod 'FontAwesome.swift'
end

target 'KarmaTests' do

end

target 'KarmaUITests' do

end

